name: binder-openms                                                                    
channels:
  - openms                                                                    
  - conda-forge                                                               
dependencies:                                                                   
  - xeus-cling                                                                
  - openms      
